[tool.poetry]
name = "3d-graphics-pygame"
version = "0.1.0"
description = ""
authors = ["ChinmayTiwari2 <<>>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
